services:
  api_front:
    build: /app/static
    depends_on:
      - api
    # command: serve -s build -l 3000
    restart: unless-stopped
    
  api:
    build: /app
    depends_on:
      # - traefik
      - pgdb
    restart: always
    expose:
    - 8000
    
  pgdb:
    # Использование готового образа postgres
    image: postgres
    # Задание переменных окружения для контейнера с postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # Задание имени контейнера для сервиса pgdb
    container_name:
      pgdb
      # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  # viber_hook:
  #   restart: always
  #   build: ./app
  #   depends_on:
  #     - api
  #   command: python sethook.py

volumes:
  pgdbdata: null
